export const TRADE_OPTIONS = [
  "AC Technician",
  "Accountant",
  "Agriculture Helper",
  "Aluminiam Feb",
  "Aluminiam Fitter",
  "Auto Electrician",
  "Barber",
  "Battery Manufacturer Worker",
  "Beauticians",
  "Bike Driver",
  "Bus Driver",
  "CNC Operator",
  "Car Washer",
  "Carpenter Furniture",
  "Carpenter Shuttering",
  "Cashier",
  "Chagehand",
  "Child Care Assistants",
  "Civil Forman",
  "Cleaner",
  "Computer Operator",
  "Cook",
  "Delivery Boy",
  "Denter",
  "Dish Washer",
  "Ductman",
  "Electrician",
  "Factory Helper",
  "False Ceiling",
  "Farmer",
  "Foreman",
  "Gardner",
  "Gypsum Carpenter",
  "HVAC",
  "Heavy Driver",
  "Helper",
  "Insulator",
  "KFC Team Member",
  "Light Driver",
  "Mason",
  "Mason Block Plaster",
  "Mason Tile",
  "Mechanic Diesel",
  "Office Boy",
  "Operator",
  "Painter Spray",
  "Painter Wall",
  "Picker and Packers",
  "Pipe Fitter",
  "Pizza Chaf",
  "Plumber",
  "Polishar",
  "Rigger",
  "Scaffolder",
  "Security Guard",
  "Sofa Maker",
  "Steel Fab",
  "Steel Fixer",
  "Supervisor",
  "Tailor",
  "Taxi Driver",
  "Turner",
  "Waiter",
  "WELDER",
  "Welder 4g/6g",
  "Welder Structure",
  "Welder(Arc,Mig )",
  "Werehouse Helper",
  "WOOD CUTTER",
] as const;

export const REGION_OPTIONS = ["Gulf", "Europe"] as const;
export type Region = typeof REGION_OPTIONS[number];
export type Trade = typeof TRADE_OPTIONS[number];
